### ISSUE TITLE
Which UV texture dataset did you use to train proGAN?

### ISSUE THREAD

**Issue by zhangxw87** [barisgecer/GANFit#2]
Hi @barisgecer, 
In the paper, you mentioned a dataset of 10,000 high resolution UV textures was used to train progressive growing GAN. I'm curious which dataset did you use?

**Comment by barisgecer** [comment]
Hi @zhangxw87 the dataset is a private texture dataset collected in 
_James Booth, Anastasios Roussos, Stefanos Zafeiriou, Allan Ponniah, and David Dunaway. A 3d morphable model learnt from 10,000 faces. In CVPR, 2016. 2_. Unfortunately due to licencing issues, there is no plan to make it public anytime soon.
